### PR TITLE
update report

### PR DESCRIPTION
**Pull request by SamarinAnton**
Code was corrected in two part
Added conclusion

### CODE REVIEW

**Review by DimaStoyanov — COMMENTED** [review]
Document size decreased by 25%. Great job!

**Comment by MikhailovNikita** [comment]
Code review done. No govnocode detected. Changes should be accepted.

**Review by nariman — APPROVED** [review]
Revolutionary! Approved!

**Review by MikhailovNikita — APPROVED** [review]
Matstat ne ochen, zato commit zaebis.

**Review by nariman — COMMENTED** [review]
Like ne glyadya!

**Review by DimaStoyanov — CHANGES_REQUESTED** [review]
It is better to use Word formulas for greater clarity.

image

**Comment by MikhailovNikita** [comment]
Предлагаю кикнуть Диму из контрибьюторов!
Ставьте лайки, подписывайтесь на канал, жмите на колокольчик.

**Comment by SamarinAnton** [comment]
I think that kiknut Dimu is a good choice

**Comment by nariman** [comment]
Звучит как революция!
Я был прав, когда писал ревью.

**Review by AlexandrZamiralov — COMMENTED** [review]
What a fortune to find a developer with common interests, for several years I have kept abreast of mathematical statistics, and now I can say for sure and categorically - the author is a genius, the work deserves the close attention of both newbies and other masters

**Review by AlexandrZamiralov — APPROVED** [review]

**Review by DimaStoyanov — APPROVED** [review]

**Pull request merged**
